### ISSUE TITLE
Error: 410 Gone

### ISSUE THREAD

**Issue by v0idum** [project-serum/serum-ts#186]
Getting this error when try to run this example https://github.com/project-serum/serum-ts/blob/master/packages/swap/examples/swap.js from swap package:
Error: 410 Gone:  {"jsonrpc":"2.0","error":{"code": 410, "message":"The RPC call or parameters have been disabled."}, "id": "3b56fc88-1bd6-4b12-86b1-42482f87a777" } 

    at ClientBrowser.callServer (/home/aven/WebstormProjects/serum-ts/packages/swap/node_modules/@solana/web3.js/lib/index.cjs.js:4423:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

W
![Screenshot from 2021-11-12 13-59-54](https://user-images.githubusercontent.com/31531518/141440660-db485bf1-a69e-45ca-8106-c9e992772b20.png)
hat is wrong?

**Comment by kinghchan** [comment]
How to re-create issue:

curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d ' {"jsonrpc":"2.0", "id":1, "method":"getProgramAccounts", "params":["9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"]} '

The program ID is the Serum DEX V3 (see link below)
https://explorer.solana.com/address/9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin/tokens

**Comment by phlqp** [comment]
Use this RPC: https://solana-api.projectserum.com

**Comment by armaniferrante** [comment]
Note that getProgramAccounts is disabled for some RPC servers. Hence the error.
