### ISSUE TITLE
market.settleFunds() returns an error

### ISSUE THREAD

**Issue by zenpoet** [project-serum/serum-ts#72]
This is for DEX V3, RAY/USDC market, 2xiv8A5xrJ7RnGdxXB42uFEkYHJjszEhaJyKKt4WaLep

📄 Settling funds...
Transaction simulation failed: Error processing Instruction 0: custom program error: 0x100076b 
    Program 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin invoke [1]
    Program 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin consumed 4284 of 200000 compute units
    Program 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin failed: custom program error: 0x100076b
2021-03-12T21:32:09.174Z 🛑 Error:
  Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x100076b
      at Connection.sendEncodedTransaction (/home/zenpoet/goldorak/node_modules/@solana/web3.js/lib/index.cjs.js:3556:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async Connection.sendRawTransaction (/home/zenpoet/goldorak/node_modules/@solana/web3.js/lib/index.cjs.js:3517:20)
      at async Connection.sendTransaction (/home/zenpoet/goldorak/node_modules/@solana/web3.js/lib/index.cjs.js:3507:12)
      at async Market._sendTransaction (/home/zenpoet/goldorak/node_modules/@project-serum/serum/lib/market.js:446:27)
      at async Market.settleFunds (/home/zenpoet/goldorak/node_modules/@project-serum/serum/lib/market.js:530:16)
      at async main (/home/zenpoet/goldorak/settle.js:18:4)

**Comment by zenpoet** [comment]
problem was that base and quote wallets were flipped. so no bug.
